### ISSUE TITLE
Adicionando o campo marca na API 

### ISSUE THREAD

**Issue by m7ez1n** [marcopandolfo/produtos-integrado#1]
Adicionei o campo Brand na API, tentei o textbox e a label na gui mas não sei como ficou por conta de não tá mexendo no Visual Studio.

```
      req.assert('brand', 'Invalid brand').notEmpty();
      brand: req.body.brand,  

```

~~Primeira vez que to fazendo uma Issue em outro repositório, não sabia como organizar isso~~

![Captura de tela de 2019-06-20 08-17-13](https://user-images.githubusercontent.com/44484286/59845456-d6ed4580-9333-11e9-9f83-980a79954422.png)

**Comment by marcopandolfo** [comment]
Obrigado
